export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";
export const AUTH_CHECK_IF_LOGGED_IN = "AUTH_CHECK_IF_LOGGED_IN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";

// Creation
export const PLAYLIST_CREATION_START = "PLAYLIST_CREATION_START";
export const PLAYLIST_CREATION_SUCCESS = "PLAYLIST_CREATION_SUCCESS";
export const PLAYLIST_CREATION_FAIL = "PLAYLIST_CREATION_FAIL";

// Playlist Gets
export const GET_PLAYLISTS_SUCCESS = "GET_PLAYLISTS_SUCCESS";
export const GET_PLAYLISTS_FAIL = "GET_PLAYLISTS_FAIL";
export const GET_PLAYLISTS = "GET_PLAYLISTS";
export const GET_FAVOURITES_SUCCESS = "GET_FAVOURITES_SUCCESS";
export const GET_FAVOURITES_FAIL = "GET_FAVOURITES_FAIL";
export const GET_FAVOURITES = "GET_FAVOURITES";
export const GET_CURRENT_PLAYLIST = "GET_CURRENT_PLAYLIST";

// Playlist Deletes and Upadtes
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL";
export const UPDATE_PLAYLIST_SUCCESS = "UPDATE_PLAYLIST_SUCCESS";
export const UPDATE_PLAYLIST_FAIL = "UPDATE_PLAYLIST_FAIL";

// Songs
export const PLAY_SONG = "PLAY_SONG";
export const PLAY_NEXT = "PLAY_NEXT";
export const ADD_SONG_SUCCESS = "ADD_SONG_SUCCESS";
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS";
export const GET_SONGS_FAIL = "GET_SONGS_FAIL";
export const DELETE_SONGS_SUCCESS = "DELETE_SONGS_SUCCESS";
export const DELETE_SONGS_FAIL = "DELETE_SONGS_FAIL";
export const GET_SONGS = "GET_SONGS";
export const GET_CURRENT_SONGS = "GET_CURRENT_SONGS";
export const HANDLE_END_SONG = "HANDLE_END_SONG";

// Queue changes
export const SET_QUEUE_REPEAT = "SET_QUEUE_REPEAT";
export const SET_QUEUE_ALL_SONGS = "SET_QUEUE_ALL_SONGS";
export const SETUP_PREV = "SETUP_PREV";
export const RESET_QUEUE = "RESET_QUEUE";
export const RESET_QUEUE_INVERTED = "RESET_QUEUE_INVERTED";

// Media Controls
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const TOGGLE_STOP = "TOGGLE_STOP";
export const TOGGLE_SKIP_SUCCESS = "TOGGLE_SKIP_SUCCESS";
export const TOGGLE_SKIP_FAIL = "TOGGLE_SKIP_FAIL";
export const TOGGLE_BACK_SUCCESS = "TOGGLE_BACK_SUCCESS";
export const TOGGLE_BACK_FAIL = "TOGGLE_BACK_FAIL";
export const TOGGLE_PAUSE = "TOGGLE_PAUSE";
export const TOGGLE_SHUFFLE_ON = "TOGGLE_SHUFFLE_ON";
export const TOGGLE_SHUFFLE_OFF = "TOGGLE_SHUFFLE_OFF";
export const TOGGLE_REPEAT_ON = "TOGGLE_REPEAT_ON";
export const TOGGLE_REPEAT_OFF = "TOGGLE_REPEAT_OFF";
export const TOGGLE_REPEAT_ONE = "TOGGLE_REPEAT_ONE";

export const AUTH_SIGNUP_RESET_STATE = "AUTH_SIGNUP_RESET_STATE";

// Search Bar
export const OPEN_SEARCH = "OPEN_SEARCH";
